_welcome:
    pattern:  /
    defaults: { _controller: AcmeDemoBundle:Welcome:index }

_demo_secured:
    resource: "@AcmeDemoBundle/Controller/SecuredController.php"
    type:     annotation

_demo:
    resource: "@AcmeDemoBundle/Controller/DemoController.php"
    type:     annotation
    prefix:   /demo
    
homepage:
    resource: "@ProjectsBlogBundle/Resources/config/routing.yml"

post:
    resource: "@ProjectsBlogBundle/Resources/config/routing.yml"

category:
    resource: "@ProjectsBlogBundle/Resources/config/routing.yml"

author:
    resource: "@ProjectsBlogBundle/Resources/config/routing.yml"

page:
    resource: "@ProjectsBlogBundle/Resources/config/routing.yml"

feed:
    resource: "@ProjectsBlogBundle/Resources/config/routing.yml"

commentsFeed:
    resource: "@ProjectsBlogBundle/Resources/config/routing.yml"

commentsToPostFeed:
    resource: "@ProjectsBlogBundle/Resources/config/routing.yml"
